image:                 php:7.0

# Composer stores all downloaded packages in the vendor/ directory.
cache:
  paths:
  - vendor/

variables:
  MYSQL_DATABASE:      joblion_tests
  MYSQL_ROOT_PASSWORD: Kaigilohgeifeph5huqu

stages:
  - test
  - deploy

# test migrations
test:migrations:
  image:               php:7.0
  services:
    - mariadb:10.1
  stage:               test
  script:
  - bash ci/dockerInstall.sh "mysql" > /dev/null
  - vendor/bin/doctrine-migrations migration:migrate -n
  - vendor/bin/doctrine orm:validate-schema

# slow mysql test on php 7.0 + mariadb 10.1 (debian stretch)
test:php:7.0:mysql:
  image:               php:7.0
  services:
    - mariadb:10.1
  stage:               test
  script:
  - bash ci/dockerInstall.sh "mysql" > /dev/null
  - phpunit --coverage-text --colors=never

# fast test on php 7.0
test:php:7.0:
  image:               php:7.0
  stage:               test
  script:
  - bash ci/dockerInstall.sh > /dev/null
  - phpunit --coverage-text --colors=never

# fast test on php 7.1
test:php:7.1:
  image:               php:7.1
  stage:               test
  script:
  - bash ci/dockerInstall.sh  > /dev/null
  - phpunit --coverage-text --colors=never

deploy_staging:
  stage:               deploy
  script:
    - bash ci/deploy.sh staging
  environment:
    name:              staging
    url:               https://staging.job-lion.et.tc/api/apidoc
  only:
  - master@job-lion/job-lion-backend
